version: "3"

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=population
      - POSTGRES_DB=population_db
      - POSTGRES_INITDB_ARGS=-A md5
    ports:
      - 5432:5432